// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx'
import * as $_app from './routes/_app.tsx'
import * as $_middleware from './routes/_middleware.ts'
import * as $admin_middleware from './routes/admin/_middleware.ts'
import * as $admin_index from './routes/admin/index.tsx'
import * as $admin_login_index from './routes/admin/login/index.tsx'
import * as $api_device_action from './routes/api/device/action.ts'
import * as $api_device_byId from './routes/api/device/byId.ts'
import * as $api_devices_id from './routes/api/devices/id.ts'
import * as $api_logout from './routes/api/logout.ts'
import * as $api_terneo from './routes/api/terneo.ts'
import * as $index from './routes/index.tsx'
import * as $TerneoDevice from './islands/TerneoDevice.tsx'
import { type Manifest } from '$fresh/server.ts'

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/_middleware.ts': $_middleware,
    './routes/admin/_middleware.ts': $admin_middleware,
    './routes/admin/index.tsx': $admin_index,
    './routes/admin/login/index.tsx': $admin_login_index,
    './routes/api/device/action.ts': $api_device_action,
    './routes/api/device/byId.ts': $api_device_byId,
    './routes/api/devices/id.ts': $api_devices_id,
    './routes/api/logout.ts': $api_logout,
    './routes/api/terneo.ts': $api_terneo,
    './routes/index.tsx': $index,
  },
  islands: {
    './islands/TerneoDevice.tsx': $TerneoDevice,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
