packages:
  - backend
  - frontend

allowBuilds:
  '@swc/core': true
  esbuild: true
  unrs-resolver: true

injectWorkspacePackages: true

minimumReleaseAgeExclude:
  - '@typescript-eslint/eslint-plugin@8.67.0'
  - '@typescript-eslint/parser@8.67.0'
  - '@typescript-eslint/project-service@8.67.0'
  - '@typescript-eslint/scope-manager@8.67.0'
  - '@typescript-eslint/tsconfig-utils@8.67.0'
  - '@typescript-eslint/type-utils@8.67.0'
  - '@typescript-eslint/types@8.67.0'
  - '@typescript-eslint/typescript-estree@8.67.0'
  - '@typescript-eslint/utils@8.67.0'
  - '@typescript-eslint/visitor-keys@8.67.0'
  - eslint-plugin-react-refresh@0.5.4
  - typescript-eslint@8.67.0

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver
