[Unit]
Description=SmartStay.app Service
After=network.target

[Service]
Type=simple
User=smartstay
WorkingDirectory=/home/smartstay/client-smartstay-app
# Environment="DENO_DIR=/home/admin/.deno"
ExecStart=npm run start
Restart=on-failure
RestartSec=10
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=smartstay-app

[Install]
WantedBy=multi-user.target
