[Unit]
Description=SmartStay.app Service
After=network.target

[Service]
Type=simple
User=smartstay
WorkingDirectory=/home/smartstay/smartstay-local
Environment=NODE_ENV=production
ExecStart=/home/smartstay/smartstay-local/start.sh
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
